[project]
name = "tndhackathont1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "django==4.2.28",
    "djangorestframework==3.16.1",
    "drf-spectacular==0.29.0",
    "python-dotenv==1.0.1",
    "requests==2.32.5",
]
