# Generated by Django 4.2.30 on 2026-06-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglog',
            name='body_part',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
